export const WMO_CONDITIONS: Record<number, string> = {
  0: "Clear Sky",
  1: "Mainly Clear",
  2: "Partly Cloudy",
  3: "Overcast",
  45: "Foggy",
  48: "Icy Fog",
  51: "Light Drizzle",
  53: "Drizzle",
  55: "Heavy Drizzle",
  61: "Light Rain",
  63: "Moderate Rain",
  65: "Heavy Rain",
  71: "Light Snow",
  73: "Moderate Snow",
  75: "Heavy Snow",
  77: "Snow Grains",
  80: "Rain Showers",
  81: "Moderate Showers",
  82: "Violent Showers",
  85: "Snow Showers",
  86: "Heavy Snow Showers",
  95: "Thunderstorm",
  96: "Thunderstorm with Hail",
  99: "Severe Thunderstorm",
};

export const FARMING_NOTES: Record<string, string> = {
  "Clear Sky": "Excellent conditions for field work and harvesting",
  "Mainly Clear": "Good day for planting and soil preparation",
  "Partly Cloudy": "Ideal for transplanting seedlings",
  "Overcast": "Good for irrigation and fertilizer application",
  "Foggy": "Monitor for fungal disease development",
  "Light Drizzle": "Delay pesticide application",
  "Drizzle": "Good soil moisture — delay spraying",
  "Heavy Drizzle": "Check drainage in low-lying fields",
  "Light Rain": "Good natural irrigation — monitor drainage",
  "Moderate Rain": "Delay field operations — check drainage",
  "Heavy Rain": "Stay off fields, risk of soil compaction",
  "Rain Showers": "Intermittent — plan short field tasks",
  "Moderate Showers": "Delay pesticide and fertilizer application",
  "Violent Showers": "Do not operate machinery — flooding risk",
  "Thunderstorm": "Stay indoors — do not operate equipment",
};
